### ISSUE TITLE
ModuleNotFoundError when executing docformatter with Python 3.10.8

### ISSUE THREAD

**Issue by martacasa** [PyCQA/docformatter#129]
I am trying to execute docformatter v1.5.0 with Python 3.10.8 and it raises the following exception:

```
Traceback (most recent call last):
  File "/home/user/.cache/pre-commit/repokrg4ehr2/py_env-python3.10/bin/docformatter", line 8, in <module>
    sys.exit(main())
  File "/home/user/.cache/pre-commit/repokrg4ehr2/py_env-python3.10/lib/python3.10/site-packages/docformatter.py", line 1145, in main
    return _main(
  File "/home/user/.cache/pre-commit/repokrg4ehr2/py_env-python3.10/lib/python3.10/site-packages/docformatter.py", line 1017, in _main
    return _format_files(
  File "/home/user/.cache/pre-commit/repokrg4ehr2/py_env-python3.10/lib/python3.10/site-packages/docformatter.py", line 1117, in _format_files
    result = format_file(
  File "/home/user/.cache/pre-commit/repokrg4ehr2/py_env-python3.10/lib/python3.10/site-packages/docformatter.py", line 957, in format_file
    encoding = detect_encoding(filename)
  File "/home/user/.cache/pre-commit/repokrg4ehr2/py_env-python3.10/lib/python3.10/site-packages/docformatter.py", line 940, in detect_encoding
    from lib2to3.pgen2 import tokenize as lib2to3_tokenize
ModuleNotFoundError: No module named 'lib2to3'
```

**Comment by h3nry-1** [comment]
I'm having the same issue with Ubuntu 20.04 and a fresh install from Python 3.10.8. 
I could solve it when i installed this package: `sudo apt install python3.10-lib2to3`, but there is probably a better solution :D

**Comment by weibullguy** [comment]
lib2to3 is part of the standard library.  It's marked for deprecation, I believe, in the 3.12 release.  I ran the test suite against v1.5.0 using a fresh install of Python 3.10.8 and all tests passed.  Given this and the solution posted by @h3nry-1, I would guess Ubuntu doesn't package lib2to3 with Python likely in preparation of it's impending deprecation.  As of now, at least on Ubuntu and derivatives, that **is** the solution.  Other distributions may or may not have the issue depending on package maintenance practices.

The ultimate solution as far as docformatter is concerned is to remove the use of the lib2to3 module.  This will happen with the next release.

**Comment by weibullguy** [comment]
@martacasa and @h3nry-1 could you try the latest 1.5.1 release to see if your lib2to3 problem is resolved?

**Comment by h3nry-1** [comment]
@weibullguy i removed the installation of `python3.10-lib2to3` and updated the docformatter to version 1.5.1: everything is working fine for me. Thank you for answering and resolving the issue
